version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medcore_db
      MYSQL_USER: medcore
      MYSQL_PASSWORD: medcorepassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # Ensure the data is stored in db_data directory inside your project

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: medcore_db
      MYSQL_USER: medcore
      MYSQL_PASSWORD: medcorepassword
      JWT_SECRET_KEY: secretkey
    depends_on:
      - mariadb

  nginx:
    build:
      context: .
      dockerfile: nginx-stacy.Dockerfile 
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./static/scripts:/usr/share/nginx/scripts
      - ./static/styles:/usr/share/nginx/styles

    depends_on:
      - flask

volumes:
  mariadb_data:
