

x-common-env: &common-env
  - POSTGRES_USER: red
  - POSTGRES_PASSWORD: red
  - POSTGRES_DB: red

services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: red-db
    environment:
      <<: *common-env
    volumes:
      - ./red.sql:/docker-entrypoint-initdb.d/red.sql
      - red_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - red_network

networks:
  red_network:
    driver: bridge

volumes:
  red_data:
    driver: local
