version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medcore_db
      MYSQL_USER: medcore
      MYSQL_PASSWORD: medcorepassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql  # Ensure the data is stored in db_data directory inside your project
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3

  flask:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: medcore_db
      MYSQL_USER: medcore
      MYSQL_PASSWORD: medcorepassword
      SECRET_KEY: secretkey
      JWT_SECRET_KEY: jwt_secretkey
    depends_on:
      - mariadb

  nginx:
    build:
      context: .
      dockerfile: nginx-stacy.Dockerfile 
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./static/scripts:/usr/share/nginx/scripts
      - ./static/styles:/usr/share/nginx/styles

    depends_on:
      - flask

  pytest:
    build:
      context: .
      dockerfile: Dockerfile.pytest
    command: pytest --junitxml=report.xml
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: medcore_db
      MYSQL_USER: medcore
      MYSQL_PASSWORD: medcorepassword
    depends_on:
      flask:
        condition: service_started
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
